CREATE TABLE food_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    food_name TEXT NOT NULL,
    calories INTEGER NOT NULL,
    protein REAL NOT NULL,
    carbs REAL NOT NULL,
    fats REAL NOT NULL,
    meal_type TEXT NOT NULL,
    serving_size TEXT,
    description TEXT
);

INSERT INTO food_items (food_name, calories, protein, carbs, fats, meal_type, serving_size, description) VALUES
("Oatmeal with Berries", 280, 8, 48, 6, "Breakfast", "1 cup cooked", "Rolled oats with blueberries and almonds"),
("Scrambled Eggs with Toast", 320, 14, 30, 12, "Breakfast", "2 eggs + 1 slice", "Whole wheat toast with 2 large eggs"),
("Greek Yogurt Parfait", 250, 15, 35, 4, "Breakfast", "1 cup", "Greek yogurt with granola and honey"),
("Whole Wheat Pancakes", 350, 10, 52, 8, "Breakfast", "2 pancakes", "Topped with maple syrup and berries"),
("Avocado Toast", 290, 11, 32, 14, "Breakfast", "1 slice bread", "Whole grain bread with mashed avocado"),
("Smoothie Bowl", 310, 12, 48, 7, "Breakfast", "1 bowl", "Banana, protein powder, granola, coconut"),
("Egg White Omelet", 180, 18, 8, 6, "Breakfast", "3 egg whites", "With spinach, tomatoes, and mushrooms"),
("Cereal with Milk", 220, 7, 42, 3, "Breakfast", "1 cup", "Whole grain cereal with low-fat milk"),
("Banana with Peanut Butter", 290, 8, 34, 14, "Breakfast", "1 banana + 2 tbsp", "Medium banana with natural peanut butter"),
("French Toast", 340, 11, 46, 10, "Breakfast", "2 slices", "Whole wheat bread with cinnamon"),
("Grilled Chicken Breast with Rice", 420, 35, 52, 5, "Lunch", "150g chicken + 1 cup rice", "Skinless chicken with brown rice"),
("Salmon Fillet with Vegetables", 480, 38, 35, 18, "Lunch", "150g salmon", "Grilled salmon with broccoli and carrots"),
("Turkey Sandwich", 380, 28, 42, 10, "Lunch", "2 slices bread", "Whole wheat with turkey and veggies"),
("Lentil Curry", 360, 18, 45, 8, "Lunch", "1.5 cups", "Red lentils with light coconut milk"),
("Grilled Fish Tacos", 380, 32, 40, 12, "Lunch", "2 tacos", "Mahi-mahi with cabbage slaw"),
("Quinoa Buddha Bowl", 420, 16, 55, 12, "Lunch", "1 bowl", "Quinoa, chickpeas, veggies, tahini dressing"),
("Beef Stir Fry", 450, 32, 48, 12, "Lunch", "1.5 cups", "Lean beef with broccoli and brown rice"),
("Chicken Caesar Salad", 380, 30, 25, 18, "Lunch", "2 cups", "Grilled chicken, whole wheat croutons"),
("Veggie Burger", 340, 18, 45, 9, "Lunch", "1 burger", "Plant-based patty with whole wheat bun"),
("Tuna Salad", 320, 32, 18, 12, "Lunch", "150g tuna", "Canned tuna with mixed greens"),
("Pork Tenderloin", 410, 40, 35, 10, "Lunch", "150g pork", "With sweet potato and green beans"),
("Chickpea Hummus Wrap", 360, 14, 48, 10, "Lunch", "1 wrap", "Whole wheat wrap with hummus and veggies"),
("Grilled Tilapia", 280, 35, 15, 8, "Dinner", "180g fillet", "White fish with lemon and herbs"),
("Lean Ground Turkey Meatballs", 350, 40, 20, 10, "Dinner", "6 meatballs", "Baked with marinara sauce"),
("Baked Cod", 240, 38, 10, 4, "Dinner", "200g fillet", "With asparagus and zucchini"),
("Grilled Chicken Thighs", 380, 35, 8, 22, "Dinner", "150g thighs", "Skinless with garlic and rosemary"),
("Lean Beef Sirloin", 420, 42, 0, 24, "Dinner", "150g steak", "Grilled with side salad"),
("Vegetable Stir Fry", 220, 8, 28, 8, "Dinner", "2 cups", "Mixed veggies with tofu"),
("Turkey Meatloaf", 340, 38, 18, 10, "Dinner", "1 slice", "With whole wheat breadcrumbs"),
("Shrimp Scampi", 280, 32, 15, 10, "Dinner", "200g shrimp", "With whole wheat pasta"),
("Chicken Breast with Sweet Potato", 380, 36, 42, 6, "Dinner", "150g chicken", "Baked with minimal oil"),
("Lentil and Vegetable Soup", 260, 15, 38, 4, "Dinner", "2 cups", "Hearty with spinach and tomatoes"),
("Baked Tofu Steak", 200, 22, 8, 10, "Dinner", "200g tofu", "Marinated and grilled"),
("Halibut with Broccoli", 320, 40, 18, 8, "Dinner", "150g fish", "Steamed with garlic"),
("Almonds", 160, 6, 6, 14, "Snack", "23 almonds", "Raw unsalted almonds"),
("Greek Yogurt", 130, 18, 9, 0, "Snack", "150g cup", "Plain, low-fat Greek yogurt"),
("Apple with Almond Butter", 210, 7, 25, 9, "Snack", "1 apple + 1 tbsp", "Fresh apple with natural almond butter"),
("Protein Bar", 200, 20, 22, 5, "Snack", "1 bar", "Whey protein energy bar"),
("Mixed Nuts", 180, 6, 8, 16, "Snack", "30g portion", "Almonds, cashews, walnuts"),
("Cottage Cheese", 110, 14, 4, 5, "Snack", "100g", "Low-fat cottage cheese"),
("Protein Shake", 180, 25, 15, 3, "Snack", "1 shake", "Whey protein with water"),
("Hummus with Veggies", 150, 5, 16, 7, "Snack", "1/4 cup + veggies", "Chickpea hummus with carrots"),
("Dark Chocolate", 170, 4, 13, 12, "Snack", "30g bar", "70% dark chocolate"),
("Banana", 90, 1, 23, 0, "Snack", "1 medium", "Fresh banana"),
("Granola Bar", 140, 4, 20, 5, "Snack", "1 bar", "Oat and honey granola bar"),
("String Cheese", 80, 7, 1, 6, "Snack", "1 stick", "Low-fat mozzarella stick");

CREATE TABLE user_metrics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    age INTEGER NOT NULL,
    gender TEXT NOT NULL,
    height REAL NOT NULL,
    weight REAL NOT NULL,
    activity_level TEXT NOT NULL,
    goal TEXT NOT NULL,
    bmi REAL,
    bmr REAL,
    daily_calories INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
